language: c
env:
    - PYTHONPATH=/usr/lib/pypy3/site-packages
before_install:
    - sudo apt-add-repository 'deb http://nikicat.github.io/pypy3-repo ./'
    - sudo apt-get update
    - sudo apt-get install pypy3 -y --force-yes
    - sudo ln -fs pypy3 /usr/bin/python
    - sudo mkdir /usr/lib/pypy3/site-packages
    - curl https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py | sudo PYTHONPATH=/usr/lib/pypy3/site-packages pypy3
    - sudo ln -fs /usr/lib/pypy3/bin/easy_install /usr/local/bin/easy_install
install:
    - sudo PYTHONPATH=/usr/lib/pypy3/site-packages easy_install tox
script:
    - /usr/lib/pypy3/bin/tox
notifications:
    hipchat:
        rooms:
            secure: Sp9KR8whmkdUOlPd6VRUEjM3evH9mtGRbRVmF8NWEhVS5iolwn1+0tjWEf9dIxWGftccI3Mw4UoTvct7CWu/2lOp2x0iLwuTYjKgXJ9T4RJbt65NYnGhsg+wzzlacQVWRUnEBje2DEBBMqsW5PT5zo8eTcNC7YN/H7kybpOLwYM=
